management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers

  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
